version: '3'
services:
 app:
    build: .
    ports:
      - "8080:8080"
 nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - app